language: ruby
rvm:
- 2.0.0
- 2.1.1
- 2.1.2
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: 2.1.2
before_script:
  - psql -c 'create database citygram_test;' -U postgres
script:
- cp .env.sample .env
- bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/citygram_test
- bundle exec rake
#notifications:
#  webhooks: http://project-monitor.codeforamerica.org/projects/77db7e4d-a05a-4ee8-b7ab-3bd29c6dd1b0/status
deploy:
  provider: heroku
  api_key:
    secure: H620R+7VCEwt8xGuziB6ZW82JJT1a5pBudT2Hq/oN4qZko4P9QSjMhuT+nhhnr0iemNIEpm24Y7i+MGOaKwXFJ+wE5yEz0jHc3w7BGRcfxZYKw8KWBrPqAFSqp1wMyo/YSAFIXOdTN2xV+19HaYUw2FCRSy9uBkn9H9cBim1V6w=
  app: citygram
  on:
    repo: CodeForAsheville/citygram
  run:
    - "bundle exec rake db:create db:migrate DATABASE_URL=postgres://venosqhgdsrtis:_zCmvyllGdYa-2lyRIXOOYRUdc@ec2-54-83-204-78.compute-1.amazonaws.com:5432/d87pb24ufllngf"
    - "rake cleanup"

