language: ruby
rvm:
- 2.0.0
- 2.1.1
- 2.1.2
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: 2.1.2
before_script:
- psql -c 'create database citygram_test;' -U postgres
script:
- cp .env.sample .env
- bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/citygram_test
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: FfsafzVEPwUgGxf6IzvMaKsJs+mxAo1L+ip8OzGz64r1e68xMXcyqlgL8SYtcxX6Lg+UbtmwxSJzAbKpVA+QkrdsfUN5vVf6zjXii85YENIQwb6aQ6L8G8nECr5QjQnaankzqxDtC8eFpuCFbVZGKRt/fqll6RYSJXlOlqXPmJQ=
  app: citygramavl
  on:
    repo: CodeForAsheville/citygram
  run:
    "bundle exec rake db:create db:migrate"
    "rake cleanup"